dist: xenial
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
services:
  - xvfb

notifications:
  email: false

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - conda env create -f conda_env.yml
  - source activate ml4bio

install:
  - pip install .

script:
  # no test cases yet so only test the import
  - python -c "import ml4bio; print(ml4bio.__version__)"
  - ml4bio &
