# Based on http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda35-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda env create -f conda_env.yml
  - activate ml4bio
  - pip install .

test_script:
  # no test cases yet so only test the import
  - python -c "import ml4bio; print(ml4bio.__version__)"
